export const GET_MEDIA_REQUEST = 'GET_MEDIA_REQUEST';
export const GET_MEDIA_SUCCESS = 'GET_MEDIA_SUCCESS';
export const GET_MEDIA_FAILED = 'GET_MEDIA_FAILED';
export const ADD_MEDIA_BY_USER = 'ADD_MEDIA_BY_USER';
export const UPDATE_AVAILABLE_IMAGES = 'UPDATE_AVAILABLE_IMAGES';
